# Generated by Django 3.2.3 on 2021-10-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210731_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubricitem',
            name='author',
        ),
    ]
