# Generated by Django 3.2.3 on 2021-10-13 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_rubricitem_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubricitem',
            name='cover',
        ),
    ]
